### ISSUE TITLE
bookmark import failing

### ISSUE THREAD

**Issue by mmehnert** [owncloud/bookmarks#29]
OC 5 fails to import my bookmark html-file that I exported from firefox.
Anyone else having problems?

When it happens, I only get

    SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(140) at [...]/lib/db.php#1031

in the log

From the bookmark app code I guess that's a problem with the bookmark title. Any particular reason the title does not have a maximum size of 4k, too?

**Comment by Chouchen** [comment]
Well, as for now, the 140 character limit is still here https://github.com/owncloud/bookmarks/blob/master/appinfo/database.xml#L30

I see 2 possibilities : 
1. increase that value (but to how much ? A title can be veeeeery long…) but the error can still persist.
2. trim the title to 140 here : https://github.com/owncloud/bookmarks/blob/master/controller/lib/bookmarks.php#L524 `$title = substr($link->nodeValue, 0, 140);`

Actually, you can mix them :laughing: but I'm new here, who takes that kind of decision?

**Comment by TtuxX** [comment]
@Chouchen Or we can completely remove this limit ? :) 
We are talking about bookmark imports, that is to say already-existing bookmarks. Those already existing bookmarks have been saved in a certain way. Thus, their titles might had already been changed/set by the user according to his will... Shouldn't we just remove this title limit ?

**Comment by Chouchen** [comment]
@TtuxX I'm no database expert but I think they already have limits for *text* type which are differents depending on the choosen database type.
I think we need to control that limit.

And I'm pretty new to owncloud dev but *maybe* the `database.xml` needs a `length` node.

**Comment by Scorry** [comment]
Error persists in OC 8.0.2 (ubuntu 14.04.2, postgresql 9.3). Pages with title longer than 140 characters can not be saved.
I resolved this changing `tytle` in `oc_bookmarks` table from `character varying(140)` to `character varying(4096)`
Page can be saved now.

**Comment by Chouchen** [comment]
Until title is more than 4096 characters.
Why that limit and not another? If you got sources, I'm interested.
Even more, if those sources say title can't be more than 4096 characters, you could do a PR changing the `database.xml` file :)

**Comment by Scorry** [comment]
It was not a reasonable choice. Just copied length from url parameter — say, just a big enough.
For a references: W3C does not limit length of title of the page, but determine that **"The title should ideally be less than 64 characters in length. ..."** ([The TITLE element in HTML](http://www.w3.org/Provider/Style/TITLE.html))
In my humble opinion the length of the stored title need to be checked and trimmed in excess, but I don't know how, sadly. I can edit db instead :)
140 characters may be quite enough for ASCII, but may be not enough for UTF. Well, may be long titles must be trimmed and full title must be copied in description field?.. User can decide how to deal with it.
Just a glimpse:

**Comment by Chouchen** [comment]
Mmmm I think you have a great idea. 
* Trim to 64 characters to comply to recommandations (or 140 to copy twitter and to stay backward compatible) 
* Put the full title in description (if empty)

We need to have feedback on this!

**Comment by Scorry** [comment]
Well, great decision. I'll vote for it if necessary.

**Comment by TtuxX** [comment]
@Scorry @Chouchen Very nice ideas, I would agree on 140 characters titles triming, however I think there would still be some issues... which are making me thinking that the very large 4096 characters title limit could be a yet imperfect (but simple) temporary "solution".  How would you plan dealing with:
- Import of bookmarks with long titles ? Should we import them, trim their title and automatically write their full titles as description if the description field is empty ? If description field is not empty, how should bookmarks app behaves ? If we do not modify description text, then finally nothing would apparently change from the current bookmarks app version behavior... :(
- If title is longer than 140 characters, if description field is empty, and if in such case you automatically copy the full-lenght title to the description field, then the app "default" behavior result will make us end-up with exactly the same title and description beginnings... It might not looks very attractive and clean.. This will also mean that user will systematically have to check/delete/modify description when adding a new bookmark...

What are your opinions/ideas regarding the possible ways to solve these problems ? :)

**Comment by Scorry** [comment]
@TtuxX :
> Import of bookmarks with long titles ? Should we import them, trim their title and automatically write their full titles as description if the description field is empty ?

... and otherwise check if full title plus newline plus existing description fit in 4096 and write it, if not — silently trim title portion in description, may be separate from old description by some recognizable symbol — for example, asterisk or **|**.

Or, as you remark, 
> This will also mean that user will systematically have to check/delete/modify description field when adding a new bookmark...

It may be a matter of user's choice. May be some options in app settings “how to deal with long titles”.

**Comment by LordVan** [comment]
I have no use for such a long title field and since i do not care about storing the rest of it personally I just edited bookmarks.php line 462+ (OC 8.0.2)

```php
$params = array(
                                $enc_url,
                                htmlspecialchars_decode($title),
                                $userid,
                                $public,
                                $description,
);
```
and changed it to this:

```php
$params = array(
                                $enc_url,
                                substr(htmlspecialchars_decode($title), 0, 140),
                                $userid,
                                $public,
                                $description,
);
```
Probably should do something similar with the description too but well that seems to not be a problem.

**Comment by Chouchen** [comment]
yeah, there are a lot of places you can do a `substr()` to "solve" this. Anyway, we're trying to make a solution everyone could enjoy :-) 

You should do a PR with that modification. That way, people in charge of this project could choose that solution in the end if that's what people wants.

**Comment by LordVan** [comment]
@Chouchen yeah i just thought i'd paste it in here in case someone wants to do that rather than mess with the db ^^..
if i can be bothered i might just add the part to copy the rest to the description field .. but my motivation is rather low for this haha

also it seems - correct me if i am wrong - that there is at least no active maintainer for this app :(

**Comment by Chouchen** [comment]
Unfortunatly, you may be right about the lack of maintainer.
Anyway, a clean PR with a commit message containing "fix #29" would appear here and be clearer IMHO.

**Comment by LordVan** [comment]
Well *if* I feel like (and have time) doing this properly instead of just one substr() then i guess i might as well do that .. just for one line i don't want to start reading git howtos/manuals again ^^

**Comment by TtuxX** [comment]
Hello @LordVan :)
> I have no use for such a long title field and since i do not care about storing the rest of it personally I just edited bookmarks.php

I perfectly get it but don't you think we could adopt a larger limit than only `140` characters ? Like  `250` characters for example ? :) (regarding the idea of `4096` characters titles limit, I think such long titles will actually never happen; and if it happens, it means that the bookmarked website's webmasters might be quite bad at making relevant content.. >.<)

I used to correct a simple bug which was making the bookmarks app to always show only 10 tags in the main window tag list, and I completely removed the limit!
In my opinion, setting abusive content restrictions to the user is a bad habit.

Given that bookmarks titles are going to get visually cut anyway when displaying from the bookmarks web interface, I think we should not be so restrictive regarding the title length (knowing that in the "worst" situation, the user can always rename and cut text manually after adding a bookmark with a long title).
What would you think about increasing this limit to let's say `250` when importing/adding a bookmark ? :)

Cc @Chouchen @Scorry

**Comment by Scorry** [comment]
Hello @TtuxX :)
Totally agree.

**Comment by LordVan** [comment]
@TtuxX , @Scorry well as I said what i wanted at that point in time was a quick fix for my problem of not being able to add some bookmarks. What length one sets for this is questionable of course ^^ I only kept the 140 cuz i had no interest in spending a lot of time on it hehe

and yes 140 might be a bit short -- although to be honest I think if someone doesn'T manage to have a meaningful title < 140 chars then they are already doing something wrong, since one does not really need the whole site navigation structure that the page is at in the title imho .. since 99,99% are not going to read it.
But I guess increasing it to e.g. 256 chars is still within reason. 4096 is well .. worth writing an email to the person who made it and asking them what is wrong with putting their content on the actual page instead of in the title. Anyway I would not waste too much time on titles > 256 (for example) chars and just trim them and give the user some - client side javascript - warning that it has been truncuated -- the biggest "problem" i had was that i was not actually getting any UI feedback why it wasn'T added (actually not even any feedback that it hadn't been added -- a quick look at the source shows me that there seems to be no error handling there) 

I mean yeah you could add a "add rest of title to description field if the title is long - and desc. is empty" but who would actually read that ... I mean i won'T for sure, and i doubt that many would

**Comment by Scorry** [comment]
@LordVan  :
> i doubt that many would
because of that in may be a user's choice.
Undoubtedly, length of title must be checked before trying to write it to database. As any other raw data, of course.

**Comment by TtuxX** [comment]
Hello @Chouchen @Scorry @LordVan :)
Anyone for a quick PR fix ? We would need a 256 char limit instead of the current 140 one and a trim for all other characters after, in order to solve this recurrent error.
We are actually debating about limit size and so on, but I think that for now it would rather be wise to expand it from 140 to 256 chars, trim the rest and get this silly issue fixed :)
If anyone want to fix it then let it know here, otherwise I will create a PR with a simple fix for it within a month. We need to get it fixed even in a basic way as it affects quite a lot of users. =/

**Comment by ege1** [comment]
There are a few things I do not understand regarding the limit for the site title:

- is there no check in the code for this limit? So I can enter whatever I want and it fails on the last step (database)?
- I assumed that it might be the title (I thought it was the "pipe" sign) and shortened it, but still was unable to save. So does it save the original title, not what I entered before saving?

The best solution in my opinion would be:

- raise limit to 255 characters
- if title exceeds that limit, show message, that title will be (or was) shortened to 255 chars. (I don't mind if you've to confirm the shortening or not, but a message would be fine)

If that is too much effort, it is also fine to not save and show error message, but allow the user to shorten the title (right now it does not use the title entered in the field but it seams like it is using the original site title). That looks like a bug to me anyway.

HTH

Erik

**Comment by Chouchen** [comment]
Well, you both got the same solution.
We just need someone to make a PR out of it :)

**Comment by ege1** [comment]
I would if I had a clue what to do.

While trying to nail it down I found the cause to my problem. The title is less than 100 characters and it still didn't save. I debugged it and found the following:

 Exception: {"Message":"An exception occurred while executing 'UPDATE \"oc_bookmarks\" SET \"lastmodified\" = cast(extract(epoch from current_timestamp) as integer)  , title = ?  WHERE \"url\" = ? and \"user_id\" = ?' with params [\"Metasploitation | Ethical Hacking for one and allMetasploitation | Ethical Hacking for one and all<\\\/title>\\n\\t<link rel=\\\"profile\\\" href=\\\"http:\\\/\\\/gmpg.org\\\/xfn\\\/11\\\">\\n\\t<link rel=\\\"pingback\\\" href=\\\"http:\\\/\\\/www.metasploitation.com\\\/xmlrpc.php\\\">\\n\\t\\n\\t<title>Metasploitation | Ethical Hacking for one and allMetasploitation | Ethical Hacking for one and all\", \"http:\\\/\\\/www.metasploitation.com\\\/\", \"ege\"]

The page source code has two titles. For me it looks like it is too greedy when searching for </title>

But the preview in the "Add a bookmark" screen is correct. It should just use this title and not the original one. Otherwise it doesn't make any sense to make it an editable input field.

**Comment by ege1** [comment]
This doesn't fix the length issue, but gives the user the possibility to shorten the title.

**Comment by ege1** [comment]
Can someone do a review on my changes, please?

**Comment by Chouchen** [comment]
I did it.

**Comment by ege1** [comment]
Sorry, had to change the approach of creating pull requests. Learned a few days ago to create a new branch. It's way easier to change stuff afterwards.

**Comment by ege1** [comment]
@Chouchen, is there something missing or wrong with the pull request?
